install:
  - pip install -U tox-travis codecov
  - yarn --cwd brew_view/static install
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
script:
  - tox
  - make -C brew_view/static/ lint coverage
after_success:
  - codecov -F backend
  - yarn --cwd brew_view/static run codecov -F frontend
