install:
  - pip install -U tox-travis codecov
  - yarn install --cwd brew_view/static
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
script:
  - tox
  - make -C brew_view/static/ test lint
after_success:
  codecov
